<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>retail-vendor-performance-analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="06_retail-vendor-performance-Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="06_retail-vendor-performance-Analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="06_retail-vendor-performance-Analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="06_retail-vendor-performance-Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="06_retail-vendor-performance-Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="06_retail-vendor-performance-Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="06_retail-vendor-performance-Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="06_retail-vendor-performance-Analysis_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="06_retail-vendor-performance-Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="06_retail-vendor-performance-Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="06_retail-vendor-performance-Analysis_files/libs/bootstrap/bootstrap-0b6f55a02c0e84a1b4f13bcc2a2cd5dc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary-and-key-recommendations" id="toc-executive-summary-and-key-recommendations" class="nav-link active" data-scroll-target="#executive-summary-and-key-recommendations">🧾 Executive Summary and Key Recommendations</a>
  <ul class="collapse">
  <li><a href="#project-overview" id="toc-project-overview" class="nav-link" data-scroll-target="#project-overview">🎯 Project Overview</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">💡 Key Findings</a></li>
  <li><a href="#strategic-recommendations" id="toc-strategic-recommendations" class="nav-link" data-scroll-target="#strategic-recommendations">🚀 Strategic Recommendations</a></li>
  <li><a href="#final-takeaway" id="toc-final-takeaway" class="nav-link" data-scroll-target="#final-takeaway">📈 Final Takeaway</a></li>
  </ul></li>
  <li><a href="#environment-setup" id="toc-environment-setup" class="nav-link" data-scroll-target="#environment-setup">⚙️ Environment Setup</a></li>
  <li><a href="#database-connection-and-data-loading" id="toc-database-connection-and-data-loading" class="nav-link" data-scroll-target="#database-connection-and-data-loading">🗄️ Database Connection and Data Loading</a>
  <ul class="collapse">
  <li><a href="#preview-of-the-dataset" id="toc-preview-of-the-dataset" class="nav-link" data-scroll-target="#preview-of-the-dataset">🔍 Preview of the Dataset</a></li>
  </ul></li>
  <li><a href="#data-pipeline-overview" id="toc-data-pipeline-overview" class="nav-link" data-scroll-target="#data-pipeline-overview">🗂️ Data Pipeline Overview</a>
  <ul class="collapse">
  <li><a href="#source-tables-and-record-counts" id="toc-source-tables-and-record-counts" class="nav-link" data-scroll-target="#source-tables-and-record-counts">Source Tables and Record Counts</a></li>
  <li><a href="#data-modeling-approach" id="toc-data-modeling-approach" class="nav-link" data-scroll-target="#data-modeling-approach">Data Modeling Approach</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">🔍 Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">📊 Summary Statistics</a></li>
  <li><a href="#distribution-of-numerical-variables" id="toc-distribution-of-numerical-variables" class="nav-link" data-scroll-target="#distribution-of-numerical-variables">📈 Distribution of Numerical Variables</a></li>
  <li><a href="#summary-statistics-insights" id="toc-summary-statistics-insights" class="nav-link" data-scroll-target="#summary-statistics-insights"><strong>Summary Statistics Insights</strong></a></li>
  </ul></li>
  <li><a href="#data-cleaning-and-preparation" id="toc-data-cleaning-and-preparation" class="nav-link" data-scroll-target="#data-cleaning-and-preparation">🧹 Data Cleaning and Preparation</a>
  <ul class="collapse">
  <li><a href="#data-filtering-criteria" id="toc-data-filtering-criteria" class="nav-link" data-scroll-target="#data-filtering-criteria">⚙️ Data Filtering Criteria</a></li>
  <li><a href="#distribution-after-cleaning" id="toc-distribution-after-cleaning" class="nav-link" data-scroll-target="#distribution-after-cleaning">📊 Distribution After Cleaning</a></li>
  </ul></li>
  <li><a href="#categorical-feature-analysis" id="toc-categorical-feature-analysis" class="nav-link" data-scroll-target="#categorical-feature-analysis">🏷️ Categorical Feature Analysis</a>
  <ul class="collapse">
  <li><a href="#top-vendors-and-products" id="toc-top-vendors-and-products" class="nav-link" data-scroll-target="#top-vendors-and-products">📊 Top Vendors and Products</a></li>
  </ul></li>
  <li><a href="#correlation-analysis" id="toc-correlation-analysis" class="nav-link" data-scroll-target="#correlation-analysis">🔗 Correlation Analysis</a>
  <ul class="collapse">
  <li><a href="#insights-from-the-heatmap" id="toc-insights-from-the-heatmap" class="nav-link" data-scroll-target="#insights-from-the-heatmap">📈 Insights from the Heatmap</a></li>
  </ul></li>
  <li><a href="#analysis-1-high-margin-low-sales-brands-promopricing-opportunities" id="toc-analysis-1-high-margin-low-sales-brands-promopricing-opportunities" class="nav-link" data-scroll-target="#analysis-1-high-margin-low-sales-brands-promopricing-opportunities">🎯 Analysis 1 — High-Margin, Low-Sales Brands (Promo/Pricing Opportunities)</a>
  <ul class="collapse">
  <li><a href="#step-1-brand-level-aggregation" id="toc-step-1-brand-level-aggregation" class="nav-link" data-scroll-target="#step-1-brand-level-aggregation">Step 1 — Brand-level aggregation</a></li>
  <li><a href="#step-2-thresholds" id="toc-step-2-thresholds" class="nav-link" data-scroll-target="#step-2-thresholds">Step 2 — Thresholds</a></li>
  <li><a href="#step-3-target-list" id="toc-step-3-target-list" class="nav-link" data-scroll-target="#step-3-target-list">Step 3 — Target list</a></li>
  <li><a href="#step-4-scatter-plot-all-brands" id="toc-step-4-scatter-plot-all-brands" class="nav-link" data-scroll-target="#step-4-scatter-plot-all-brands">Step 4 — Scatter plot (all brands)</a></li>
  <li><a href="#step-5-zoomed-view-mitigate-outliers" id="toc-step-5-zoomed-view-mitigate-outliers" class="nav-link" data-scroll-target="#step-5-zoomed-view-mitigate-outliers">Step 5 — Zoomed view (mitigate outliers)</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">🧩 Findings</a></li>
  </ul></li>
  <li><a href="#analysis-2-top-vendors-and-brands-by-sales" id="toc-analysis-2-top-vendors-and-brands-by-sales" class="nav-link" data-scroll-target="#analysis-2-top-vendors-and-brands-by-sales">💰 Analysis 2 — Top Vendors and Brands by Sales</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">📊 Summary</a></li>
  <li><a href="#insights" id="toc-insights" class="nav-link" data-scroll-target="#insights">📈 Insights</a></li>
  </ul></li>
  <li><a href="#analysis-3-vendor-contribution-to-total-purchases" id="toc-analysis-3-vendor-contribution-to-total-purchases" class="nav-link" data-scroll-target="#analysis-3-vendor-contribution-to-total-purchases">📦 Analysis 3 — Vendor Contribution to Total Purchases</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">📊 Overview</a></li>
  <li><a href="#key-findings-1" id="toc-key-findings-1" class="nav-link" data-scroll-target="#key-findings-1">🔎 Key Findings</a></li>
  <li><a href="#business-insight" id="toc-business-insight" class="nav-link" data-scroll-target="#business-insight">💡 Business Insight</a></li>
  </ul></li>
  <li><a href="#analysis-4-vendor-dependency-and-bulk-purchase-efficiency" id="toc-analysis-4-vendor-dependency-and-bulk-purchase-efficiency" class="nav-link" data-scroll-target="#analysis-4-vendor-dependency-and-bulk-purchase-efficiency">🧮 Analysis 4 — Vendor Dependency and Bulk Purchase Efficiency</a>
  <ul class="collapse">
  <li><a href="#question-1-how-much-of-total-procurement-depends-on-top-vendors" id="toc-question-1-how-much-of-total-procurement-depends-on-top-vendors" class="nav-link" data-scroll-target="#question-1-how-much-of-total-procurement-depends-on-top-vendors">Question 1 — How much of total procurement depends on top vendors?</a></li>
  <li><a href="#question-2-does-purchasing-in-bulk-reduce-the-unit-price" id="toc-question-2-does-purchasing-in-bulk-reduce-the-unit-price" class="nav-link" data-scroll-target="#question-2-does-purchasing-in-bulk-reduce-the-unit-price">Question 2 — Does purchasing in bulk reduce the unit price?</a></li>
  </ul></li>
  <li><a href="#analysis-5-inventory-turnover-and-capital-locked-in-unsold-stock" id="toc-analysis-5-inventory-turnover-and-capital-locked-in-unsold-stock" class="nav-link" data-scroll-target="#analysis-5-inventory-turnover-and-capital-locked-in-unsold-stock">📦 Analysis 5 — Inventory Turnover and Capital Locked in Unsold Stock</a>
  <ul class="collapse">
  <li><a href="#low-inventory-turnover" id="toc-low-inventory-turnover" class="nav-link" data-scroll-target="#low-inventory-turnover">🔄 Low Inventory Turnover</a></li>
  <li><a href="#capital-locked-in-unsold-inventory" id="toc-capital-locked-in-unsold-inventory" class="nav-link" data-scroll-target="#capital-locked-in-unsold-inventory">💰 Capital Locked in Unsold Inventory</a></li>
  <li><a href="#insights-1" id="toc-insights-1" class="nav-link" data-scroll-target="#insights-1">📈 Insights</a></li>
  </ul></li>
  <li><a href="#analysis-6-profit-margin-confidence-intervals-for-top-vs.-low-vendors" id="toc-analysis-6-profit-margin-confidence-intervals-for-top-vs.-low-vendors" class="nav-link" data-scroll-target="#analysis-6-profit-margin-confidence-intervals-for-top-vs.-low-vendors">💹 Analysis 6 — Profit Margin Confidence Intervals for Top vs.&nbsp;Low Vendors</a>
  <ul class="collapse">
  <li><a href="#statistical-summary" id="toc-statistical-summary" class="nav-link" data-scroll-target="#statistical-summary">🧮 Statistical Summary</a></li>
  <li><a href="#insights-from-the-distribution" id="toc-insights-from-the-distribution" class="nav-link" data-scroll-target="#insights-from-the-distribution">📊 Insights from the Distribution</a></li>
  <li><a href="#business-implications" id="toc-business-implications" class="nav-link" data-scroll-target="#business-implications">💡 Business Implications</a></li>
  </ul></li>
  <li><a href="#analysis-7-hypothesis-testing-profit-margin-differences-between-vendor-groups" id="toc-analysis-7-hypothesis-testing-profit-margin-differences-between-vendor-groups" class="nav-link" data-scroll-target="#analysis-7-hypothesis-testing-profit-margin-differences-between-vendor-groups">🧾 Analysis 7 — Hypothesis Testing: Profit Margin Differences Between Vendor Groups</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">🧠 Hypotheses</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">⚙️ Method</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">📊 Results</a></li>
  <li><a href="#business-insight-1" id="toc-business-insight-1" class="nav-link" data-scroll-target="#business-insight-1">💡 Business Insight</a></li>
  </ul></li>
  <li><a href="#author" id="toc-author" class="nav-link" data-scroll-target="#author">👋 Author</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">🧭 Project Overview</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This report analyzes <strong>retail-vendor performance</strong> by examining sales, pricing, and purchasing patterns across multiple brands and suppliers. The goal is to identify key insights that can inform better <strong>vendor management</strong> and <strong>pricing strategies</strong>.</p>
<section id="executive-summary-and-key-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary-and-key-recommendations">🧾 Executive Summary and Key Recommendations</h2>
<section id="project-overview" class="level3">
<h3 class="anchored" data-anchor-id="project-overview">🎯 Project Overview</h3>
<p>This project analyzed vendor performance data to identify <strong>sales efficiency, profit margins, and inventory utilization</strong> across multiple suppliers. Using SQL, Python, and statistical methods, the analysis provided insights into <strong>pricing strategies, vendor concentration, and profitability trends</strong>.</p>
<hr>
</section>
<section id="key-findings" class="level3">
<h3 class="anchored" data-anchor-id="key-findings">💡 Key Findings</h3>
<ul>
<li><p><strong>Vendor Concentration:</strong> The top 10 vendors contribute <strong>~66% of total purchases</strong>, indicating high procurement dependency on a few large suppliers.</p></li>
<li><p><strong>High-Margin, Low-Sales Brands:</strong> Several brands have <strong>strong profit margins but weak sales</strong> — ideal candidates for <strong>targeted promotions or pricing adjustments</strong>.</p></li>
<li><p><strong>Bulk Purchasing Efficiency:</strong> Larger orders benefit from <strong>~72% lower unit costs</strong>, confirming economies of scale in purchasing.</p></li>
<li><p><strong>Inventory Concerns:</strong> About <strong>$2.71M</strong> is tied up in unsold inventory, with a few vendors holding the majority of slow-moving stock.</p></li>
<li><p><strong>Profit Margin Disparity:</strong> Low-performing vendors maintain <strong>higher average profit margins (~41%)</strong>, while high-performing vendors operate at <strong>lower margins (~31%)</strong>, a difference confirmed by t-tests (p &lt; 0.001).</p></li>
</ul>
<hr>
</section>
<section id="strategic-recommendations" class="level3">
<h3 class="anchored" data-anchor-id="strategic-recommendations">🚀 Strategic Recommendations</h3>
<ol type="1">
<li><p><strong>Promote High-Margin, Low-Sales Brands:</strong> Introduce targeted marketing, bundling, or shelf placement incentives to boost sales volume.</p></li>
<li><p><strong>Negotiate with Key Vendors:</strong> Use concentration data to secure <strong>bulk discounts</strong> and <strong>improved contract terms</strong> with top suppliers.</p></li>
<li><p><strong>Optimize Inventory Management:</strong> Identify slow-moving SKUs and consider <strong>clearance strategies</strong> or <strong>stock realignment</strong> to release tied-up capital.</p></li>
<li><p><strong>Enhance Vendor Profitability:</strong></p>
<ul>
<li>For top vendors: focus on <strong>cost optimization</strong> and <strong>pricing efficiency</strong>.</li>
<li>For smaller vendors: support with <strong>distribution expansion</strong> and <strong>competitive pricing models</strong>.</li>
</ul></li>
<li><p><strong>Implement Performance Dashboards:</strong> Develop an automated vendor KPI dashboard (sales, margin, turnover) to track performance trends over time.</p></li>
</ol>
<hr>
</section>
<section id="final-takeaway" class="level3">
<h3 class="anchored" data-anchor-id="final-takeaway">📈 Final Takeaway</h3>
<p>The analysis reveals a <strong>dual market structure</strong> — a small set of large-volume vendors driving sales and numerous niche vendors sustaining profitability. Balancing both through <strong>data-driven pricing, procurement, and promotion strategies</strong> can enhance overall vendor ecosystem performance and improve profit growth.</p>
</section>
</section>
<section id="environment-setup" class="level2">
<h2 class="anchored" data-anchor-id="environment-setup">⚙️ Environment Setup</h2>
<p>We begin by importing the required Python libraries for data manipulation, statistical analysis, and visualization.</p>
<div id="98925ccb" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sqlalchemy <span class="im">import</span> create_engine, text</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Explanation:</strong> - <code>pandas</code> and <code>numpy</code> handle data wrangling and numerical operations. - <code>matplotlib</code> and <code>seaborn</code> create professional data visualizations. - <code>sqlalchemy</code> manages database connections. - <code>scipy.stats</code> supports statistical testing. - Warnings are suppressed for cleaner outputs.</p>
</section>
<section id="database-connection-and-data-loading" class="level2">
<h2 class="anchored" data-anchor-id="database-connection-and-data-loading">🗄️ Database Connection and Data Loading</h2>
<p>The dataset is stored in a PostgreSQL database. We use environment variables to securely manage credentials and establish a connection.</p>
<p><strong>Explanation:</strong> - <code>.env</code> variables keep credentials secure and prevent hardcoding sensitive information. - The connection string uses <code>sqlalchemy</code> and <code>psycopg2</code> to create a PostgreSQL engine. - Data is extracted from the table <code>mart.vendor_sales_summary</code>, which contains vendor-level sales details.</p>
<section id="preview-of-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="preview-of-the-dataset">🔍 Preview of the Dataset</h3>
<div id="d1508280" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating database connection</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dotenv <span class="im">import</span> load_dotenv</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>load_dotenv()</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>user <span class="op">=</span> os.getenv(<span class="st">"PGUSER"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>pwd  <span class="op">=</span> os.getenv(<span class="st">"PGPASSWORD"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>host <span class="op">=</span> os.getenv(<span class="st">"PGHOST"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>port <span class="op">=</span> os.getenv(<span class="st">"PGPORT"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>db   <span class="op">=</span> os.getenv(<span class="st">"PGDATABASE"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>engine <span class="op">=</span> create_engine(<span class="ss">f"postgresql+psycopg2://</span><span class="sc">{</span>user<span class="sc">}</span><span class="ss">:</span><span class="sc">{</span>pwd<span class="sc">}</span><span class="ss">@</span><span class="sc">{</span>host<span class="sc">}</span><span class="ss">:</span><span class="sc">{</span>port<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>db<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>pd.read_sql_query(<span class="st">"select * from mart.vendor_sales_summary"</span>, engine)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">vendor_number</th>
<th data-quarto-table-cell-role="th">vendor_name</th>
<th data-quarto-table-cell-role="th">brand</th>
<th data-quarto-table-cell-role="th">description</th>
<th data-quarto-table-cell-role="th">purchase_price</th>
<th data-quarto-table-cell-role="th">actual_price</th>
<th data-quarto-table-cell-role="th">volume</th>
<th data-quarto-table-cell-role="th">total_purchase_quantity</th>
<th data-quarto-table-cell-role="th">total_purchase_dollars</th>
<th data-quarto-table-cell-role="th">total_sales_quantity</th>
<th data-quarto-table-cell-role="th">total_sales_dollars</th>
<th data-quarto-table-cell-role="th">total_sales_price</th>
<th data-quarto-table-cell-role="th">total_excise_tax</th>
<th data-quarto-table-cell-role="th">freight_cost</th>
<th data-quarto-table-cell-role="th">gross_profit</th>
<th data-quarto-table-cell-role="th">profit_margin</th>
<th data-quarto-table-cell-role="th">stock_turnover</th>
<th data-quarto-table-cell-role="th">sales_to_purchase_ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1128</td>
<td>BROWN-FORMAN CORP</td>
<td>1233</td>
<td>Jack Daniels No 7 Black</td>
<td>26.27</td>
<td>36.99</td>
<td>1750.0</td>
<td>145080.0</td>
<td>3811251.60</td>
<td>142049.0</td>
<td>5101919.51</td>
<td>672819.31</td>
<td>260999.20</td>
<td>68601.68</td>
<td>1290667.91</td>
<td>25.297693</td>
<td>0.979108</td>
<td>1.338647</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>4425</td>
<td>MARTIGNETTI COMPANIES</td>
<td>3405</td>
<td>Tito's Handmade Vodka</td>
<td>23.19</td>
<td>28.99</td>
<td>1750.0</td>
<td>164038.0</td>
<td>3804041.22</td>
<td>160247.0</td>
<td>4819073.49</td>
<td>561512.37</td>
<td>294438.66</td>
<td>144929.24</td>
<td>1015032.27</td>
<td>21.062810</td>
<td>0.976890</td>
<td>1.266830</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>17035</td>
<td>PERNOD RICARD USA</td>
<td>8068</td>
<td>Absolut 80 Proof</td>
<td>18.24</td>
<td>24.99</td>
<td>1750.0</td>
<td>187407.0</td>
<td>3418303.68</td>
<td>187140.0</td>
<td>4538120.60</td>
<td>461140.15</td>
<td>343854.07</td>
<td>123780.22</td>
<td>1119816.92</td>
<td>24.675786</td>
<td>0.998575</td>
<td>1.327594</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3960</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>4261</td>
<td>Capt Morgan Spiced Rum</td>
<td>16.17</td>
<td>22.99</td>
<td>1750.0</td>
<td>201682.0</td>
<td>3261197.94</td>
<td>200412.0</td>
<td>4475972.88</td>
<td>420050.01</td>
<td>368242.80</td>
<td>257032.07</td>
<td>1214774.94</td>
<td>27.139908</td>
<td>0.993703</td>
<td>1.372493</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3960</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>3545</td>
<td>Ketel One Vodka</td>
<td>21.89</td>
<td>29.99</td>
<td>1750.0</td>
<td>138109.0</td>
<td>3023206.01</td>
<td>135838.0</td>
<td>4223107.62</td>
<td>545778.28</td>
<td>249587.83</td>
<td>257032.07</td>
<td>1199901.61</td>
<td>28.412764</td>
<td>0.983556</td>
<td>1.396897</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Initial Observation:</strong> The dataset provides detailed information about vendors, brands, product descriptions, and corresponding purchase and selling prices. This structure forms a strong foundation for evaluating <strong>pricing efficiency</strong>, <strong>vendor competitiveness</strong>, and <strong>sales volume performance</strong> across brands.</p>
</section>
</section>
<section id="data-pipeline-overview" class="level2">
<h2 class="anchored" data-anchor-id="data-pipeline-overview">🗂️ Data Pipeline Overview</h2>
<p>Before performing the analysis, multiple source tables were extracted from the PostgreSQL database and transformed into a unified analytical dataset.</p>
<section id="source-tables-and-record-counts" class="level3">
<h3 class="anchored" data-anchor-id="source-tables-and-record-counts">Source Tables and Record Counts</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Table Name</th>
<th style="text-align: right;">Row Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">begin_inventory</td>
<td style="text-align: right;">206,529</td>
</tr>
<tr class="even">
<td style="text-align: left;">end_inventory</td>
<td style="text-align: right;">224,489</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purchase_prices</td>
<td style="text-align: right;">12,261</td>
</tr>
<tr class="even">
<td style="text-align: left;">purchases</td>
<td style="text-align: right;">2,372,474</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sales</td>
<td style="text-align: right;">12,825,363</td>
</tr>
<tr class="even">
<td style="text-align: left;">vendor_invoice</td>
<td style="text-align: right;">5,543</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="data-modeling-approach" class="level3">
<h3 class="anchored" data-anchor-id="data-modeling-approach">Data Modeling Approach</h3>
<ol type="1">
<li><p><strong>Raw Layer:</strong> Original transactional data loaded from multiple operational tables.</p></li>
<li><p><strong>Staging Layer (stg):</strong> Standardized column formats, validated joins between purchases and sales, and removed incomplete vendor records.</p></li>
<li><p><strong>Mart Layer:</strong> Created the <strong><code>mart.vendor_sales_summary</code></strong> table containing ~10K aggregated records by vendor and brand. This dataset served as the foundation for subsequent <strong>exploratory, statistical, and profitability analyses</strong>.</p></li>
</ol>
<hr>
<p><strong>Outcome:</strong> A clean, analysis-ready dataset combining sales, purchase, inventory, and vendor-level information — enabling precise performance and margin evaluations.</p>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda">🔍 Exploratory Data Analysis (EDA)</h2>
<p>Before proceeding with advanced modeling or statistical testing, it’s essential to explore the dataset to understand its structure, detect anomalies, and identify patterns.</p>
<p>Previously, we examined multiple tables in the database to determine which key variables should be included in our final dataset. In this phase, we analyze the resultant table — <code>mart.vendor_sales_summary</code> — to assess data quality and distribution across all features.</p>
<section id="summary-statistics" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics">📊 Summary Statistics</h3>
<p>The table below summarizes key descriptive statistics for all numeric and categorical variables in the dataset. This helps identify missing values, detect potential outliers, and understand central tendencies and variability.</p>
<p><strong>Key Insights from Summary Statistics:</strong> - The dataset contains <strong>10,692 records</strong>, representing multiple vendors and brands across a wide range of products. - <code>vendor_name</code> has <strong>128 unique vendors</strong>, while <code>brand</code> shows <strong>over 10,600 unique entries</strong>, suggesting that most brands are tied to specific vendors. - <code>purchase_price</code> (mean ≈ 24.38, max ≈ 5681.81) and <code>actual_price</code> (mean ≈ 35.64, max ≈ 7499.99) show <strong>extreme upper outliers</strong>, possibly reflecting premium or imported items. - <code>profit_margin</code> has a <strong>mean of -15.89</strong> with a very large standard deviation (≈ 447), indicating that several products were sold below cost or with inconsistent pricing. - <code>gross_profit</code> ranges widely (from -52,002 to 1,290,667), confirming the presence of both profitable and loss-making transactions. - The <code>sales_to_purchase_ratio</code> varies dramatically (mean ≈ 2.55, max ≈ 352.9), showing substantial disparities in how efficiently vendors convert purchases into sales. - <code>stock_turnover</code> values are generally low (median ≈ 0.98), suggesting <strong>slow-moving inventory</strong> for many vendors, with a few outliers that exhibit rapid turnover. - Columns like <code>total_sales_dollars</code> and <code>total_purchase_dollars</code> have high variance, reflecting <strong>significant differences in vendor scale</strong> — some vendors dominate sales volume, while others operate in niche segments.</p>
<p><strong>Data Quality Observations:</strong> - A few metrics (e.g., <code>total_sales_quantity</code>, <code>gross_profit</code>, <code>profit_margin</code>) have slightly fewer observations than total rows, indicating <strong>missing data</strong> in certain vendor entries. - Large standard deviations across most numeric columns highlight potential <strong>skewness and heavy-tailed distributions</strong>, which will require transformation or outlier handling.</p>
<div id="a4e9bc86" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(<span class="st">"select * from mart.vendor_sales_summary"</span>, engine)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#summary statistics.</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>df.describe().T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">vendor_number</td>
<td>10692.0</td>
<td>10650.649458</td>
<td>18753.519148</td>
<td>2.000000</td>
<td>3951.000000</td>
<td>7153.000000</td>
<td>9552.000000</td>
<td>2.013590e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">purchase_price</td>
<td>10692.0</td>
<td>24.385303</td>
<td>109.269375</td>
<td>0.360000</td>
<td>6.840000</td>
<td>10.455000</td>
<td>19.482500</td>
<td>5.681810e+03</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">actual_price</td>
<td>10692.0</td>
<td>35.643671</td>
<td>148.246016</td>
<td>0.490000</td>
<td>10.990000</td>
<td>15.990000</td>
<td>28.990000</td>
<td>7.499990e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">volume</td>
<td>10692.0</td>
<td>847.360550</td>
<td>664.309212</td>
<td>50.000000</td>
<td>750.000000</td>
<td>750.000000</td>
<td>750.000000</td>
<td>2.000000e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">total_purchase_quantity</td>
<td>10692.0</td>
<td>3140.886831</td>
<td>11095.086769</td>
<td>1.000000</td>
<td>36.000000</td>
<td>262.000000</td>
<td>1975.750000</td>
<td>3.376600e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">total_purchase_dollars</td>
<td>10692.0</td>
<td>30106.693372</td>
<td>123067.799627</td>
<td>0.710000</td>
<td>453.457500</td>
<td>3655.465000</td>
<td>20738.245000</td>
<td>3.811252e+06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">total_sales_quantity</td>
<td>10514.0</td>
<td>3129.583317</td>
<td>11037.801407</td>
<td>1.000000</td>
<td>36.000000</td>
<td>280.000000</td>
<td>1985.000000</td>
<td>3.349390e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">total_sales_dollars</td>
<td>10514.0</td>
<td>42954.173834</td>
<td>168977.755843</td>
<td>1.980000</td>
<td>809.820000</td>
<td>5599.700000</td>
<td>29524.250000</td>
<td>5.101920e+06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">total_sales_price</td>
<td>10514.0</td>
<td>19111.958773</td>
<td>45264.605387</td>
<td>0.990000</td>
<td>334.890000</td>
<td>3020.085000</td>
<td>16442.477500</td>
<td>6.728193e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">total_excise_tax</td>
<td>10514.0</td>
<td>1804.263569</td>
<td>11065.659557</td>
<td>0.060000</td>
<td>5.382500</td>
<td>50.425000</td>
<td>436.730000</td>
<td>3.682428e+05</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">freight_cost</td>
<td>10692.0</td>
<td>61433.763214</td>
<td>60938.458032</td>
<td>0.090000</td>
<td>14069.870000</td>
<td>50293.620000</td>
<td>79528.990000</td>
<td>2.570321e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">gross_profit</td>
<td>10514.0</td>
<td>12364.618776</td>
<td>46576.616345</td>
<td>-52002.780000</td>
<td>66.975000</td>
<td>1496.490000</td>
<td>8970.040000</td>
<td>1.290668e+06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">profit_margin</td>
<td>10514.0</td>
<td>-15.885227</td>
<td>447.289882</td>
<td>-23730.638953</td>
<td>15.353839</td>
<td>30.778375</td>
<td>40.210967</td>
<td>9.971666e+01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">stock_turnover</td>
<td>10514.0</td>
<td>1.735689</td>
<td>6.067081</td>
<td>0.002817</td>
<td>0.829761</td>
<td>0.983431</td>
<td>1.042183</td>
<td>2.745000e+02</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">sales_to_purchase_ratio</td>
<td>10514.0</td>
<td>2.546789</td>
<td>8.524047</td>
<td>0.004196</td>
<td>1.181388</td>
<td>1.444635</td>
<td>1.672548</td>
<td>3.529286e+02</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
<section id="distribution-of-numerical-variables" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-numerical-variables">📈 Distribution of Numerical Variables</h3>
<p>The histograms below visualize the distribution of all numeric columns in the dataset. These plots reveal important characteristics of the data such as skewness, outliers, and concentration ranges.</p>
<p><strong>Observations:</strong> - Most numerical variables are <strong>right-skewed</strong>, indicating a small number of vendors with extremely high values. - Metrics like <code>total_sales_dollars</code> and <code>gross_profit</code> show heavy tails, consistent with a few dominant vendors driving the majority of sales. - The <code>profit_margin</code> distribution contains negative values, suggesting some transactions may have been made at a loss or under promotional discounts. - Continuous variables such as <code>freight_cost</code> and <code>stock_turnover</code> show more varied patterns, warranting further analysis in subsequent sections.</p>
<hr>
<div id="4080338b" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>numerical_cols<span class="op">=</span>df.select_dtypes(include<span class="op">=</span>np.number).columns</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">10</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(numerical_cols):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">4</span>,<span class="dv">4</span>,i<span class="op">+</span><span class="dv">1</span>) <span class="co">#Adjust grid layout as needed</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    sns.histplot(df[col],kde<span class="op">=</span><span class="va">True</span>, bins<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>to see what are the outliers we are going to use box plots.</p>
<div id="7d57506c" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">10</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(numerical_cols):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">4</span>,<span class="dv">4</span>,i<span class="op">+</span><span class="dv">1</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    sns.boxplot(y<span class="op">=</span>df[col])</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary-statistics-insights" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics-insights"><strong>Summary Statistics Insights</strong></h3>
<section id="negative-zero-values" class="level4">
<h4 class="anchored" data-anchor-id="negative-zero-values"><strong>Negative &amp; Zero Values</strong></h4>
<ul>
<li><strong>Gross Profit:</strong> Minimum value is <strong>-52,002.78</strong>, indicating losses. Some products or transactions may be selling at a loss due to high costs or selling at discounts lower than the purchase price.</li>
<li><strong>Profit Margin:</strong> Has a minimum of approximately <strong>-∞</strong>, which suggests cases where revenue is zero or even lower than costs.</li>
<li><strong>Total Sales Quantity &amp; Sales Dollars:</strong> Minimum values are <strong>0</strong>, meaning some products were purchased but never sold. These could be slow-moving or obsolete stock.</li>
</ul>
</section>
<section id="outliers-indicated-by-high-standard-deviations" class="level4">
<h4 class="anchored" data-anchor-id="outliers-indicated-by-high-standard-deviations"><strong>Outliers Indicated by High Standard Deviations</strong></h4>
<ul>
<li><strong>Purchase &amp; Actual Prices:</strong> The max values (<strong>5,681.81</strong> &amp; <strong>7,499.99</strong>) are significantly higher than the mean (<strong>24.39</strong> &amp; <strong>35.64</strong>), indicating potential premium products.</li>
<li><strong>Freight Cost:</strong> Huge variation, from <strong>0.09</strong> to <strong>257,032.07</strong>, suggests logistics inefficiencies or bulk shipments.</li>
<li><strong>Stock Turnover:</strong> Ranges from <strong>0</strong> to <strong>274.5</strong>, implying some products sell extremely fast while others remain in stock indefinitely.
<ul>
<li>A value <strong>greater than 1</strong> indicates that sold quantity for that product is higher than purchased quantity, possibly due to older stock being used to fulfill sales.</li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="data-cleaning-and-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-and-preparation">🧹 Data Cleaning and Preparation</h2>
<p>After the initial exploration, it was evident that several records contained <strong>negative or zero values</strong> for key financial metrics such as <code>gross_profit</code>, <code>profit_margin</code>, and <code>total_sales_quantity</code>. Such inconsistencies likely stem from data entry errors, returns, or transactions not representing valid sales. To ensure analytical accuracy, these records were filtered out before proceeding with further analysis.</p>
<hr>
<section id="data-filtering-criteria" class="level3">
<h3 class="anchored" data-anchor-id="data-filtering-criteria">⚙️ Data Filtering Criteria</h3>
<p>We retained only those records that met the following conditions: - <code>gross_profit</code> &gt; 0 — ensures that only profitable or valid transactions are included. - <code>profit_margin</code> &gt; 0 — removes loss-making or invalid entries. - <code>total_sales_quantity</code> &gt; 0 — excludes records without actual sales activity.</p>
<p>After applying these filters, the dataset reduced from <strong>10,692 to 8,564 records</strong>, removing approximately <strong>20% of invalid or incomplete entries</strong>.</p>
<hr>
<div id="bf93288f" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#filtering out the data by removing inconsistencies.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span> pd.read_sql_query(<span class="st">"""</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="st">   select *</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="st">   from mart.vendor_sales_summary</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="st">   where gross_profit&gt;0</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="st">   and profit_margin&gt;0</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="st">   and total_sales_quantity&gt;0</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>, engine)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">vendor_number</th>
<th data-quarto-table-cell-role="th">vendor_name</th>
<th data-quarto-table-cell-role="th">brand</th>
<th data-quarto-table-cell-role="th">description</th>
<th data-quarto-table-cell-role="th">purchase_price</th>
<th data-quarto-table-cell-role="th">actual_price</th>
<th data-quarto-table-cell-role="th">volume</th>
<th data-quarto-table-cell-role="th">total_purchase_quantity</th>
<th data-quarto-table-cell-role="th">total_purchase_dollars</th>
<th data-quarto-table-cell-role="th">total_sales_quantity</th>
<th data-quarto-table-cell-role="th">total_sales_dollars</th>
<th data-quarto-table-cell-role="th">total_sales_price</th>
<th data-quarto-table-cell-role="th">total_excise_tax</th>
<th data-quarto-table-cell-role="th">freight_cost</th>
<th data-quarto-table-cell-role="th">gross_profit</th>
<th data-quarto-table-cell-role="th">profit_margin</th>
<th data-quarto-table-cell-role="th">stock_turnover</th>
<th data-quarto-table-cell-role="th">sales_to_purchase_ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1128</td>
<td>BROWN-FORMAN CORP</td>
<td>1233</td>
<td>Jack Daniels No 7 Black</td>
<td>26.27</td>
<td>36.99</td>
<td>1750.0</td>
<td>145080.0</td>
<td>3811251.60</td>
<td>142049</td>
<td>5101919.51</td>
<td>672819.31</td>
<td>260999.20</td>
<td>68601.68</td>
<td>1290667.91</td>
<td>25.297693</td>
<td>0.979108</td>
<td>1.338647</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>4425</td>
<td>MARTIGNETTI COMPANIES</td>
<td>3405</td>
<td>Tito's Handmade Vodka</td>
<td>23.19</td>
<td>28.99</td>
<td>1750.0</td>
<td>164038.0</td>
<td>3804041.22</td>
<td>160247</td>
<td>4819073.49</td>
<td>561512.37</td>
<td>294438.66</td>
<td>144929.24</td>
<td>1015032.27</td>
<td>21.062810</td>
<td>0.976890</td>
<td>1.266830</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>17035</td>
<td>PERNOD RICARD USA</td>
<td>8068</td>
<td>Absolut 80 Proof</td>
<td>18.24</td>
<td>24.99</td>
<td>1750.0</td>
<td>187407.0</td>
<td>3418303.68</td>
<td>187140</td>
<td>4538120.60</td>
<td>461140.15</td>
<td>343854.07</td>
<td>123780.22</td>
<td>1119816.92</td>
<td>24.675786</td>
<td>0.998575</td>
<td>1.327594</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3960</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>4261</td>
<td>Capt Morgan Spiced Rum</td>
<td>16.17</td>
<td>22.99</td>
<td>1750.0</td>
<td>201682.0</td>
<td>3261197.94</td>
<td>200412</td>
<td>4475972.88</td>
<td>420050.01</td>
<td>368242.80</td>
<td>257032.07</td>
<td>1214774.94</td>
<td>27.139908</td>
<td>0.993703</td>
<td>1.372493</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3960</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>3545</td>
<td>Ketel One Vodka</td>
<td>21.89</td>
<td>29.99</td>
<td>1750.0</td>
<td>138109.0</td>
<td>3023206.01</td>
<td>135838</td>
<td>4223107.62</td>
<td>545778.28</td>
<td>249587.83</td>
<td>257032.07</td>
<td>1199901.61</td>
<td>28.412764</td>
<td>0.983556</td>
<td>1.396897</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8559</td>
<td>9815</td>
<td>WINE GROUP INC</td>
<td>8527</td>
<td>Concannon Glen Ellen Wh Zin</td>
<td>1.32</td>
<td>4.99</td>
<td>750.0</td>
<td>2.0</td>
<td>2.64</td>
<td>5</td>
<td>15.95</td>
<td>10.96</td>
<td>0.55</td>
<td>27100.41</td>
<td>13.31</td>
<td>83.448276</td>
<td>2.500000</td>
<td>6.041667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8560</td>
<td>8004</td>
<td>SAZERAC CO INC</td>
<td>5683</td>
<td>Dr McGillicuddy's Apple Pie</td>
<td>0.39</td>
<td>0.49</td>
<td>50.0</td>
<td>6.0</td>
<td>2.34</td>
<td>134</td>
<td>65.66</td>
<td>1.47</td>
<td>7.04</td>
<td>50293.62</td>
<td>63.32</td>
<td>96.436186</td>
<td>22.333333</td>
<td>28.059829</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8561</td>
<td>3924</td>
<td>HEAVEN HILL DISTILLERIES</td>
<td>9123</td>
<td>Deep Eddy Vodka</td>
<td>0.74</td>
<td>0.99</td>
<td>50.0</td>
<td>2.0</td>
<td>1.48</td>
<td>2</td>
<td>1.98</td>
<td>0.99</td>
<td>0.10</td>
<td>14069.87</td>
<td>0.50</td>
<td>25.252525</td>
<td>1.000000</td>
<td>1.337838</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8562</td>
<td>3960</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>6127</td>
<td>The Club Strawbry Margarita</td>
<td>1.47</td>
<td>1.99</td>
<td>200.0</td>
<td>1.0</td>
<td>1.47</td>
<td>72</td>
<td>143.28</td>
<td>77.61</td>
<td>15.12</td>
<td>257032.07</td>
<td>141.81</td>
<td>98.974037</td>
<td>72.000000</td>
<td>97.469388</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8563</td>
<td>7245</td>
<td>PROXIMO SPIRITS INC.</td>
<td>3065</td>
<td>Three Olives Grape Vodka</td>
<td>0.71</td>
<td>0.99</td>
<td>50.0</td>
<td>1.0</td>
<td>0.71</td>
<td>86</td>
<td>85.14</td>
<td>33.66</td>
<td>4.46</td>
<td>38994.78</td>
<td>84.43</td>
<td>99.166079</td>
<td>86.000000</td>
<td>119.915493</td>
</tr>
</tbody>
</table>

<p>8564 rows × 18 columns</p>
</div>
</div>
</div>
</section>
<section id="distribution-after-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="distribution-after-cleaning">📊 Distribution After Cleaning</h3>
<p>The histograms below display the distributions of numerical variables after cleaning. Compared to the earlier plots, the cleaned dataset shows <strong>reduced skewness and fewer extreme outliers</strong>, particularly for profitability and price-related columns.</p>
<p><strong>Key Observations:</strong> - The <code>profit_margin</code> distribution now centers around <strong>25%–40%</strong>, reflecting a more realistic profitability range. - <code>gross_profit</code> and <code>total_sales_price</code> remain right-skewed, indicating that a few large vendors still dominate total earnings — a normal characteristic of vendor sales data. - The overall spread of cost-related variables such as <code>freight_cost</code> has narrowed, confirming that most invalid or anomalous cost records were successfully removed. - Metrics such as <code>stock_turnover</code> and <code>sales_to_purchase_ratio</code> continue to exhibit long tails, showing operational variability among vendors that will be explored further.</p>
<hr>
<p><strong>Conclusion:</strong> This cleaning step ensures that subsequent analyses focus on <strong>valid, profit-generating vendor transactions</strong>, reducing bias from incorrect or incomplete data. The resulting dataset is now consistent, reliable, and ready for <strong>comparative performance analysis</strong> across vendors and brands.</p>
<div id="0be98a02" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">10</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(numerical_cols):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">4</span>,<span class="dv">4</span>,i<span class="op">+</span><span class="dv">1</span>) <span class="co">#Adjust grid layout as needed</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    sns.histplot(df[col],kde<span class="op">=</span><span class="va">True</span>, bins<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="categorical-feature-analysis" class="level2">
<h2 class="anchored" data-anchor-id="categorical-feature-analysis">🏷️ Categorical Feature Analysis</h2>
<p>Next, we explore the key categorical variables — <strong>vendors</strong> and <strong>product descriptions</strong> — to identify the most frequent entities in the dataset.</p>
<hr>
<section id="top-vendors-and-products" class="level3">
<h3 class="anchored" data-anchor-id="top-vendors-and-products">📊 Top Vendors and Products</h3>
<p>The charts below display the <strong>top 10 vendors</strong> and <strong>top 10 products</strong> based on record frequency.</p>
<div id="16259a0d" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>categorical_cols<span class="op">=</span> [<span class="st">'vendor_name'</span>, <span class="st">'description'</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">5</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(categorical_cols):</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">1</span>,<span class="dv">2</span>,i<span class="op">+</span><span class="dv">1</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    sns.countplot(y<span class="op">=</span>df[col], order <span class="op">=</span>df[col].value_counts().index[:<span class="dv">10</span>]) <span class="co">#top 10 categories</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f"count plot of </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Insights:</strong> - <strong>MARTIGNETTI COMPANIES</strong> dominates the dataset, followed by <strong>M S Walker Inc</strong> and <strong>Ultra Beverage Company LLP</strong>. - Major players like <strong>Perfecta Wines</strong>, <strong>E &amp; J Gallo Winery</strong>, and <strong>Diageo North America Inc</strong> also have strong representation. - Among products, <strong>Southern Comfort</strong>, <strong>Bacardi Superior Rum</strong>, and <strong>Jägermeister Liqueur</strong> appear most frequently. - Repeated entries such as <em>Southern Comfort</em> and <em>Southern Comfort 100 Proof</em> suggest SKU-level tracking.</p>
<hr>
<p><strong>Summary:</strong> The dataset is concentrated among a few large vendors and well-known brands, indicating that future comparisons should adjust for vendor scale to ensure balanced performance insights.</p>
</section>
</section>
<section id="correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis">🔗 Correlation Analysis</h2>
<p>To examine how numerical variables relate to one another, we computed the <strong>correlation matrix</strong> and visualized it using a heatmap.</p>
<div id="f6e764f0" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlational heatmap</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">8</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>correlation_matrix<span class="op">=</span>df[numerical_cols].corr()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>sns.heatmap(correlation_matrix, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".2f"</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, linewidths<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"correlation heatmap"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="insights-from-the-heatmap" class="level3">
<h3 class="anchored" data-anchor-id="insights-from-the-heatmap">📈 Insights from the Heatmap</h3>
<ul>
<li><strong>Pricing Link:</strong> <code>purchase_price</code> and <code>actual_price</code> show an almost perfect correlation (<strong>r = 0.99</strong>), confirming a cost-plus pricing strategy.</li>
<li><strong>Sales–Purchase Sync:</strong> Strong correlation between <code>total_purchase_dollars</code> and <code>total_sales_dollars</code> (<strong>r = 0.96</strong>) indicates that higher procurement typically leads to higher sales.</li>
<li><strong>Profit Follows Sales:</strong> <code>gross_profit</code> correlates strongly with sales metrics (<strong>r ≈ 0.96</strong>), suggesting top-selling items contribute most to profit.</li>
<li><strong>Tax Consistency:</strong> <code>total_excise_tax</code> aligns closely with total sales (<strong>r = 0.98</strong>), reflecting accurate taxation.</li>
<li><strong>Profit Margin Variability:</strong> Weak correlations between <code>profit_margin</code> and other metrics imply inconsistent profitability across products.</li>
<li><strong>Inventory Efficiency:</strong> Moderate correlation between <code>stock_turnover</code> and <code>profit_margin</code> (<strong>r = 0.42</strong>) shows faster-selling products tend to be more profitable.</li>
<li><strong>Vendor Neutrality:</strong> <code>vendor_number</code> has negligible correlation with performance variables, confirming no vendor ID bias.</li>
</ul>
<hr>
<p><strong>Summary:</strong> Sales, tax, and profit metrics are tightly linked, but profitability varies significantly across products — signaling opportunities for <strong>pricing optimization</strong> and <strong>inventory efficiency improvements</strong>.</p>
</section>
</section>
<section id="analysis-1-high-margin-low-sales-brands-promopricing-opportunities" class="level2">
<h2 class="anchored" data-anchor-id="analysis-1-high-margin-low-sales-brands-promopricing-opportunities">🎯 Analysis 1 — High-Margin, Low-Sales Brands (Promo/Pricing Opportunities)</h2>
<p><strong>Business Objective:</strong> Find brands that <strong>sell little</strong> but have <strong>strong profit margins</strong> — prime candidates for targeted promotions or price optimization.</p>
<section id="step-1-brand-level-aggregation" class="level3">
<h3 class="anchored" data-anchor-id="step-1-brand-level-aggregation">Step 1 — Brand-level aggregation</h3>
<p><em>(Runs the first code block: build <code>brand_performance</code> with <code>total_sales_dollars</code> and mean <code>profit_margin</code>.)</em></p>
<div id="e37c9f94" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>brand_performance<span class="op">=</span>df.groupby(<span class="st">'description'</span>).agg({</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_sales_dollars'</span>:<span class="st">'sum'</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'profit_margin'</span>: <span class="st">'mean'</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>}).reset_index()</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>brand_performance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">description</th>
<th data-quarto-table-cell-role="th">total_sales_dollars</th>
<th data-quarto-table-cell-role="th">profit_margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>(RI) 1</td>
<td>21519.09</td>
<td>18.060661</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>.nparalleled Svgn Blanc</td>
<td>1094.63</td>
<td>29.978166</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>10 Span Cab Svgn CC</td>
<td>2703.89</td>
<td>20.937612</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>10 Span Chard CC</td>
<td>3325.56</td>
<td>27.806445</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>10 Span Pnt Gris Monterey Cy</td>
<td>2082.22</td>
<td>32.226182</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7702</td>
<td>Zorvino Vyds Sangiovese</td>
<td>10579.03</td>
<td>29.525675</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7703</td>
<td>Zuccardi Q Malbec</td>
<td>1639.18</td>
<td>23.981503</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7704</td>
<td>Zum Rsl</td>
<td>10857.34</td>
<td>32.675038</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7705</td>
<td>Zwack Liqueur</td>
<td>227.88</td>
<td>16.653502</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7706</td>
<td>von Buhl Jazz Rsl</td>
<td>1359.11</td>
<td>90.773374</td>
</tr>
</tbody>
</table>

<p>7707 rows × 3 columns</p>
</div>
</div>
</div>
</section>
<section id="step-2-thresholds" class="level3">
<h3 class="anchored" data-anchor-id="step-2-thresholds">Step 2 — Thresholds</h3>
<p><em>(Runs the second code block: compute the 15th-percentile sales and 85th-percentile margin thresholds.)</em> These create objective cutoffs for “low sales” and “high margin.”</p>
<div id="b2794aa9" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>low_sales_threshold<span class="op">=</span>brand_performance[<span class="st">'total_sales_dollars'</span>].quantile(<span class="fl">0.15</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>high_margin_threshold<span class="op">=</span>brand_performance[<span class="st">'profit_margin'</span>].quantile(<span class="fl">0.85</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(low_sales_threshold, high_margin_threshold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>560.299 64.97017552750113</code></pre>
</div>
</div>
</section>
<section id="step-3-target-list" class="level3">
<h3 class="anchored" data-anchor-id="step-3-target-list">Step 3 — Target list</h3>
<p><em>(Runs the third code block: filter into <code>target_brands</code> and display the table, sorted by sales.)</em> <strong>Interpretation:</strong> Brands listed here are <strong>high-margin underperformers</strong> — strong candidates for <strong>awareness campaigns</strong>, <strong>bundling</strong>, <strong>shelf placement</strong>, or <strong>price testing</strong>.</p>
<div id="3deef781" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter brand with low sales but high performance margins.</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>target_brands<span class="op">=</span> brand_performance[</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    (brand_performance[<span class="st">'total_sales_dollars'</span>]<span class="op">&lt;=</span>low_sales_threshold) <span class="op">&amp;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    (brand_performance[<span class="st">'profit_margin'</span>]<span class="op">&gt;=</span>high_margin_threshold)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"brands with low sales but high profit margins:"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>display(target_brands.sort_values(<span class="st">'total_sales_dollars'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>brands with low sales but high profit margins:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">description</th>
<th data-quarto-table-cell-role="th">total_sales_dollars</th>
<th data-quarto-table-cell-role="th">profit_margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">6199</td>
<td>Santa Rita Organic Svgn Bl</td>
<td>9.99</td>
<td>66.466466</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2369</td>
<td>Debauchery Pnt Nr</td>
<td>11.58</td>
<td>65.975820</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2070</td>
<td>Concannon Glen Ellen Wh Zin</td>
<td>15.95</td>
<td>83.448276</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2188</td>
<td>Crown Royal Apple</td>
<td>27.86</td>
<td>89.806174</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6237</td>
<td>Sauza Sprklg Wild Berry Marg</td>
<td>27.96</td>
<td>82.153076</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5074</td>
<td>Nanbu Bijin Southern Beauty</td>
<td>535.68</td>
<td>76.747312</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2271</td>
<td>Dad's Hat Rye Whiskey</td>
<td>538.89</td>
<td>81.851584</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">57</td>
<td>A Bichot Clos Marechaudes</td>
<td>539.94</td>
<td>67.740860</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6245</td>
<td>Sbragia Home Ranch Merlot</td>
<td>549.75</td>
<td>66.444748</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3326</td>
<td>Goulee Cos d'Estournel 10</td>
<td>558.87</td>
<td>69.434752</td>
</tr>
</tbody>
</table>

<p>198 rows × 3 columns</p>
</div>
</div>
</div>
<hr>
</section>
<section id="step-4-scatter-plot-all-brands" class="level3">
<h3 class="anchored" data-anchor-id="step-4-scatter-plot-all-brands">Step 4 — Scatter plot (all brands)</h3>
<p><em>(Runs the fourth code block: scatter of <code>total_sales_dollars</code> vs.&nbsp;<code>profit_margin</code>, with thresholds and highlighted targets.)</em> <strong>Read the chart:</strong> - <strong>Upper-left quadrant</strong> = <strong>low sales / high margin</strong> → <strong>focus</strong>. - <strong>Lower-right</strong> = high sales / low margin → margin recovery opportunities (outside this analysis’ scope).</p>
<div id="e87650ea" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>brand_performance, x<span class="op">=</span><span class="st">'total_sales_dollars'</span>, y<span class="op">=</span><span class="st">'profit_margin'</span>, color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'All brands'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>target_brands, x<span class="op">=</span><span class="st">'total_sales_dollars'</span>, y<span class="op">=</span><span class="st">'profit_margin'</span>, color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'Target brands'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>plt.axhline(high_margin_threshold, linestyle<span class="op">=</span><span class="st">'--'</span>, color<span class="op">=</span><span class="st">'black'</span>, label<span class="op">=</span><span class="st">"High Margin Threshold"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>plt.axvline(low_sales_threshold, linestyle<span class="op">=</span><span class="st">'--'</span>, color<span class="op">=</span><span class="st">'black'</span>, label<span class="op">=</span><span class="st">"Los sales Threshold"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"total sales ($)"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"profit margin (%)"</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"brands for promotional or pricing adjustments"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-5-zoomed-view-mitigate-outliers" class="level3">
<h3 class="anchored" data-anchor-id="step-5-zoomed-view-mitigate-outliers">Step 5 — Zoomed view (mitigate outliers)</h3>
<p><em>(Runs the fifth code block: re-plot after subsetting brands with <code>total_sales_dollars</code> &lt; <strong>8,000</strong>.)</em> This makes <strong>low-revenue, high-margin brands</strong> easier to spot visually.</p>
<hr>
<div id="4f9a7911" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>brand_performance_segment<span class="op">=</span> brand_performance[brand_performance[<span class="st">'total_sales_dollars'</span>]<span class="op">&lt;</span><span class="dv">8000</span>]</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>brand_performance_segment, x<span class="op">=</span><span class="st">'total_sales_dollars'</span>, y<span class="op">=</span><span class="st">'profit_margin'</span>, color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'All brands'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>target_brands, x<span class="op">=</span><span class="st">'total_sales_dollars'</span>, y<span class="op">=</span><span class="st">'profit_margin'</span>, color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'Target brands'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.axhline(high_margin_threshold, linestyle<span class="op">=</span><span class="st">'--'</span>, color<span class="op">=</span><span class="st">'black'</span>, label<span class="op">=</span><span class="st">"High Margin Threshold"</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>plt.axvline(low_sales_threshold, linestyle<span class="op">=</span><span class="st">'--'</span>, color<span class="op">=</span><span class="st">'black'</span>, label<span class="op">=</span><span class="st">"Los sales Threshold"</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"total sales ($)"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"profit margin (%)"</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"brands for promotional or pricing adjustments"</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="findings" class="level3">
<h3 class="anchored" data-anchor-id="findings">🧩 Findings</h3>
<ul>
<li><p>The red cluster in the <strong>upper-left quadrant</strong> represents brands with <strong>high profit margins but low total sales</strong>. These are strong candidates for <strong>promotional campaigns or price adjustments</strong> to boost volume without hurting margins.</p></li>
<li><p>The <strong>majority of brands</strong> fall below the high-margin threshold, showing that overall profitability is <strong>modest</strong> and could benefit from margin optimization.</p></li>
<li><p>The distinct gap between the red and blue regions indicates that these high-margin brands are <strong>systematically underperforming in sales</strong>, not just random outliers.</p></li>
<li><p>Since these brands already yield healthy profit percentages, even a <strong>small increase in sales volume</strong> can have a <strong>large incremental impact</strong> on total profit.</p></li>
<li><p>The scatter confirms a <strong>non-linear sales–margin relationship</strong> — boosting sales does not necessarily erode margins, suggesting room for <strong>controlled promotions or cross-selling</strong>.</p></li>
</ul>
<hr>
<p><strong>Business Takeaway:</strong> A subset of brands with <strong>high profitability but low visibility</strong> presents an immediate opportunity. Strategic actions such as <strong>targeted advertising, bundling, or slight price reductions</strong> could enhance turnover while maintaining strong margins.</p>
</section>
</section>
<section id="analysis-2-top-vendors-and-brands-by-sales" class="level2">
<h2 class="anchored" data-anchor-id="analysis-2-top-vendors-and-brands-by-sales">💰 Analysis 2 — Top Vendors and Brands by Sales</h2>
<p><strong>Business Objective:</strong> Identify which vendors and brands generate the <strong>highest total sales</strong> to highlight key revenue drivers.</p>
<div id="96701a49" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>top_vendors<span class="op">=</span> df.groupby(<span class="st">"vendor_name"</span>)[<span class="st">"total_sales_dollars"</span>].<span class="bu">sum</span>().nlargest(<span class="dv">10</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>top_brands<span class="op">=</span> df.groupby(<span class="st">"description"</span>)[<span class="st">"total_sales_dollars"</span>].<span class="bu">sum</span>().nlargest(<span class="dv">10</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>top_vendors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>vendor_name
DIAGEO NORTH AMERICA INC      67990099.42
MARTIGNETTI COMPANIES         39330359.36
PERNOD RICARD USA             32063196.19
JIM BEAM BRANDS COMPANY       31423020.46
BACARDI USA INC               24854817.14
CONSTELLATION BRANDS INC      24218745.65
E &amp; J GALLO WINERY            18399899.46
BROWN-FORMAN CORP             18247230.65
ULTRA BEVERAGE COMPANY LLP    16502544.31
M S WALKER INC                14706458.51
Name: total_sales_dollars, dtype: float64</code></pre>
</div>
</div>
<hr>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">📊 Summary</h3>
<p>We aggregated <code>total_sales_dollars</code> at both the <strong>vendor</strong> and <strong>brand (description)</strong> levels, selecting the top 10 performers by total sales.</p>
<p><strong>Top Vendors (by total sales):</strong> - <strong>DIAGEO NORTH AMERICA INC</strong> leads with approximately <strong>$67.99M</strong>, far exceeding other distributors. - <strong>MARTIGNETTI COMPANIES</strong> and <strong>PERNOD RICARD USA</strong> follow with <strong>$39.33M</strong> and <strong>$32.06M</strong>, respectively. - The top five vendors collectively contribute a major share of overall revenue, showing strong concentration in a few market leaders.</p>
<p><strong>Top Brands (by total sales):</strong> - <strong>Jack Daniels No 7 Black</strong> tops the list at <strong>$7.96M</strong>, closely followed by <strong>Tito’s Handmade Vodka</strong> (<strong>$7.40M</strong>) and <strong>Grey Goose Vodka</strong> (<strong>$7.21M</strong>). - Well-known premium spirits dominate the top 10 list, emphasizing <strong>brand recognition and consumer loyalty</strong> as key performance drivers.</p>
<hr>
<div id="5e043065" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> format_dollars(value):</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> value <span class="op">&gt;=</span> <span class="dv">1_000_000</span>:</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>value<span class="op">/</span><span class="dv">1_000_000</span><span class="sc">:.2f}</span><span class="ss">M"</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> value <span class="op">&gt;=</span> <span class="dv">1_000</span>:</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>value<span class="op">/</span><span class="dv">1_000</span><span class="sc">:.2f}</span><span class="ss">k"</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">str</span>(value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="e4dfd94e" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>top_brands.<span class="bu">apply</span>(<span class="kw">lambda</span> x: format_dollars(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>description
Jack Daniels No 7 Black    7.96M
Tito's Handmade Vodka      7.40M
Grey Goose Vodka           7.21M
Capt Morgan Spiced Rum     6.36M
Absolut 80 Proof           6.24M
Jameson Irish Whiskey      5.72M
Ketel One Vodka            5.07M
Baileys Irish Cream        4.15M
Kahlua                     3.60M
Tanqueray                  3.46M
Name: total_sales_dollars, dtype: object</code></pre>
</div>
</div>
<div id="2ba549eb" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot for top vendors</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ax1<span class="op">=</span>sns.barplot(y<span class="op">=</span>top_vendors.index, x<span class="op">=</span>top_vendors.values, palette<span class="op">=</span><span class="st">"Blues_r"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"top 10 vendors by sales"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar <span class="kw">in</span> ax1.patches:</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    ax1.text(bar.get_width()<span class="op">+</span> (bar.get_width()<span class="op">*</span><span class="fl">0.02</span>),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>             bar.get_y()<span class="op">+</span> bar.get_height()<span class="op">/</span><span class="dv">2</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>             format_dollars(bar.get_width()),</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co"># plot for top brands</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>ax2<span class="op">=</span>sns.barplot(y<span class="op">=</span>top_brands.index.astype(<span class="bu">str</span>), x<span class="op">=</span>top_brands.values, palette<span class="op">=</span><span class="st">"Reds_r"</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Top 10 brands by sales"</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar <span class="kw">in</span> ax2.patches:</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>    ax2.text(bar.get_width()<span class="op">+</span> (bar.get_width()<span class="op">*</span><span class="fl">0.02</span>),</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>             bar.get_y()<span class="op">+</span>bar.get_height()<span class="op">/</span><span class="dv">2</span>,</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>             format_dollars(bar.get_width()),</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="insights" class="level3">
<h3 class="anchored" data-anchor-id="insights">📈 Insights</h3>
<ul>
<li>The <strong>vendor landscape is top-heavy</strong>, with a small number of suppliers accounting for most sales — suggesting strong vendor leverage and bargaining power.</li>
<li><strong>Whiskey and vodka brands</strong> dominate revenue, confirming high demand for premium liquor categories.</li>
<li>Smaller vendors and emerging brands might need <strong>marketing support</strong> or <strong>product diversification</strong> to compete in this concentrated market.</li>
</ul>
<p><strong>Summary Takeaway:</strong> The sales distribution underscores a <strong>highly consolidated market</strong> led by major vendors and globally recognized brands. These insights can guide partnership prioritization, negotiation strategy, and promotional planning.</p>
</section>
</section>
<section id="analysis-3-vendor-contribution-to-total-purchases" class="level2">
<h2 class="anchored" data-anchor-id="analysis-3-vendor-contribution-to-total-purchases">📦 Analysis 3 — Vendor Contribution to Total Purchases</h2>
<p><strong>Business Objective:</strong> Identify which vendors contribute the most to total purchase dollars to understand supplier concentration and purchasing dependency.</p>
<hr>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview">📊 Overview</h3>
<p>The dataset was grouped by <code>vendor_name</code> to calculate: - Total <strong>purchase dollars</strong>, <strong>sales dollars</strong>, and <strong>gross profit</strong> per vendor. - Each vendor’s <strong>purchase contribution percentage</strong> (share of total purchases). - The <strong>cumulative contribution</strong> to visualize top contributors via a Pareto chart.</p>
<hr>
<div id="b15f57b9" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>vendor_performance<span class="op">=</span> df.groupby(<span class="st">'vendor_name'</span>).agg({</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_purchase_dollars'</span>: <span class="st">'sum'</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'gross_profit'</span>: <span class="st">'sum'</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_sales_dollars'</span>: <span class="st">'sum'</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>}).reset_index()</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>vendor_performance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">vendor_name</th>
<th data-quarto-table-cell-role="th">total_purchase_dollars</th>
<th data-quarto-table-cell-role="th">gross_profit</th>
<th data-quarto-table-cell-role="th">total_sales_dollars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>ADAMBA IMPORTS INTL INC</td>
<td>446.16</td>
<td>258.37</td>
<td>704.53</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>ALISA CARR BEVERAGES</td>
<td>25698.12</td>
<td>78772.82</td>
<td>104470.94</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>ALTAMAR BRANDS LLC</td>
<td>11706.20</td>
<td>4000.61</td>
<td>15706.81</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>AMERICAN SPIRITS EXCHANGE</td>
<td>934.08</td>
<td>577.08</td>
<td>1511.16</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>AMERICAN VINTAGE BEVERAGE</td>
<td>104435.68</td>
<td>35167.85</td>
<td>139603.53</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">114</td>
<td>WEIN BAUER INC</td>
<td>42694.64</td>
<td>13522.49</td>
<td>56217.13</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">115</td>
<td>WESTERN SPIRITS BEVERAGE CO</td>
<td>298416.86</td>
<td>106837.97</td>
<td>405254.83</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">116</td>
<td>WILLIAM GRANT &amp; SONS INC</td>
<td>5876538.26</td>
<td>1693337.94</td>
<td>7569876.20</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">117</td>
<td>WINE GROUP INC</td>
<td>5203801.17</td>
<td>3100242.11</td>
<td>8304043.28</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">118</td>
<td>ZORVINO VINEYARDS</td>
<td>86122.71</td>
<td>38066.88</td>
<td>124189.59</td>
</tr>
</tbody>
</table>

<p>119 rows × 4 columns</p>
</div>
</div>
</div>
<p>Here, I am adding a new column for purchase contribution</p>
<div id="5731b83b" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>vendor_performance[<span class="st">'purchase_contribution_percentage'</span>]<span class="op">=</span> <span class="dv">100</span><span class="op">*</span>vendor_performance[<span class="st">'total_purchase_dollars'</span>]<span class="op">/</span>vendor_performance[<span class="st">'total_purchase_dollars'</span>].<span class="bu">sum</span>()</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>vendor_performance<span class="op">=</span><span class="bu">round</span>(vendor_performance.sort_values(<span class="st">'purchase_contribution_percentage'</span>, ascending<span class="op">=</span><span class="va">False</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The Top vendors can be seen the the table below.</p>
<div id="f649bf49" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>top_vendors<span class="op">=</span>vendor_performance.head(<span class="dv">10</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>top_vendors[<span class="st">'total_sales_dollars'</span>]<span class="op">=</span>top_vendors[<span class="st">'total_sales_dollars'</span>].<span class="bu">apply</span>(format_dollars)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>top_vendors[<span class="st">'total_purchase_dollars'</span>]<span class="op">=</span>top_vendors[<span class="st">'total_purchase_dollars'</span>].<span class="bu">apply</span>(format_dollars)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>top_vendors[<span class="st">'gross_profit'</span>]<span class="op">=</span>top_vendors[<span class="st">'gross_profit'</span>].<span class="bu">apply</span>(format_dollars)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>top_vendors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">vendor_name</th>
<th data-quarto-table-cell-role="th">total_purchase_dollars</th>
<th data-quarto-table-cell-role="th">gross_profit</th>
<th data-quarto-table-cell-role="th">total_sales_dollars</th>
<th data-quarto-table-cell-role="th">purchase_contribution_percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">25</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>50.10M</td>
<td>17.89M</td>
<td>67.99M</td>
<td>16.30</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">57</td>
<td>MARTIGNETTI COMPANIES</td>
<td>25.50M</td>
<td>13.83M</td>
<td>39.33M</td>
<td>8.30</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">68</td>
<td>PERNOD RICARD USA</td>
<td>23.85M</td>
<td>8.21M</td>
<td>32.06M</td>
<td>7.76</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">46</td>
<td>JIM BEAM BRANDS COMPANY</td>
<td>23.49M</td>
<td>7.93M</td>
<td>31.42M</td>
<td>7.64</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>BACARDI USA INC</td>
<td>17.43M</td>
<td>7.42M</td>
<td>24.85M</td>
<td>5.67</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">20</td>
<td>CONSTELLATION BRANDS INC</td>
<td>15.27M</td>
<td>8.95M</td>
<td>24.22M</td>
<td>4.97</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>BROWN-FORMAN CORP</td>
<td>13.24M</td>
<td>5.01M</td>
<td>18.25M</td>
<td>4.31</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>E &amp; J GALLO WINERY</td>
<td>12.07M</td>
<td>6.33M</td>
<td>18.40M</td>
<td>3.93</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">106</td>
<td>ULTRA BEVERAGE COMPANY LLP</td>
<td>11.17M</td>
<td>5.34M</td>
<td>16.50M</td>
<td>3.63</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">53</td>
<td>M S WALKER INC</td>
<td>9.76M</td>
<td>4.94M</td>
<td>14.71M</td>
<td>3.18</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="86ae5b9f" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>top_vendors[<span class="st">'cumulative_contribution_percentage'</span>]<span class="op">=</span>top_vendors[<span class="st">'purchase_contribution_percentage'</span>].cumsum()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cc8b4674" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the figure and primary axis</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>fig, ax1 <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Bar plot for Purchase Contribution % ---</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>top_vendors[<span class="st">'vendor_name'</span>],</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>top_vendors[<span class="st">'purchase_contribution_percentage'</span>],</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    palette<span class="op">=</span><span class="st">"mako"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax1</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Add value labels on bars</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, value <span class="kw">in</span> <span class="bu">enumerate</span>(top_vendors[<span class="st">'purchase_contribution_percentage'</span>]):</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    ax1.text(i, value <span class="op">-</span> <span class="dv">1</span>, <span class="ss">f"</span><span class="sc">{</span>value<span class="sc">}</span><span class="ss">%"</span>, ha<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, color<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Line plot for Cumulative Contribution % ---</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> ax1.twinx()</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>ax2.plot(</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    top_vendors[<span class="st">'vendor_name'</span>],</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    top_vendors[<span class="st">'cumulative_contribution_percentage'</span>],</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'red'</span>,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="st">'o'</span>,</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">'dashed'</span>,</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">'cumulative contribution percentage'</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Axis labels and formatting ---</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>ax1.set_xticklabels(top_vendors[<span class="st">'vendor_name'</span>], rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Purchase Contribution %'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Cumulative Contribution %'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Vendors'</span>)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Pareto Chart: Vendor Contribution to Total Purchases'</span>)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Horizontal reference line</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>ax2.axhline(y<span class="op">=</span><span class="dv">100</span>, color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Legend and display</span></span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>ax2.legend(loc<span class="op">=</span><span class="st">'upper right'</span>)</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-24-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="key-findings-1" class="level3">
<h3 class="anchored" data-anchor-id="key-findings-1">🔎 Key Findings</h3>
<ul>
<li><strong>DIAGEO NORTH AMERICA INC</strong> dominates with <strong>16.3%</strong> of total purchases — nearly double that of the next vendor.</li>
<li><strong>MARTIGNETTI COMPANIES</strong>, <strong>PERNOD RICARD USA</strong>, and <strong>JIM BEAM BRANDS COMPANY</strong> each contribute around <strong>7–8%</strong>, forming the next major tier.</li>
<li>The <strong>top 10 vendors</strong> together account for roughly <strong>65% of total purchases</strong>, confirming a <strong>highly concentrated supplier base</strong>.</li>
<li>The cumulative line (red) in the Pareto chart illustrates a <strong>steep initial climb</strong>, showing that a small set of vendors drive the majority of procurement spend.</li>
</ul>
<hr>
</section>
<section id="business-insight" class="level3">
<h3 class="anchored" data-anchor-id="business-insight">💡 Business Insight</h3>
<ul>
<li>The <strong>80/20 rule</strong> is evident — a few key vendors control most purchasing activity.</li>
<li>This suggests opportunities for:
<ul>
<li><strong>Negotiating better terms</strong> with top suppliers.</li>
<li><strong>Diversifying vendors</strong> to reduce dependency risk.</li>
<li>Prioritizing <strong>performance monitoring</strong> for high-volume vendors.</li>
</ul></li>
</ul>
<hr>
<p><strong>Summary:</strong> Procurement activity is heavily concentrated among a few suppliers, emphasizing the need for strategic vendor management and risk mitigation.</p>
</section>
</section>
<section id="analysis-4-vendor-dependency-and-bulk-purchase-efficiency" class="level2">
<h2 class="anchored" data-anchor-id="analysis-4-vendor-dependency-and-bulk-purchase-efficiency">🧮 Analysis 4 — Vendor Dependency and Bulk Purchase Efficiency</h2>
<section id="question-1-how-much-of-total-procurement-depends-on-top-vendors" class="level3">
<h3 class="anchored" data-anchor-id="question-1-how-much-of-total-procurement-depends-on-top-vendors">Question 1 — How much of total procurement depends on top vendors?</h3>
<p>The <strong>top 10 vendors</strong> collectively account for <strong>65.69% of total purchases</strong>, as shown below. This indicates a strong dependency on a small number of suppliers.</p>
<div id="ec26c54c" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>total_contribution <span class="op">=</span> <span class="bu">round</span>(top_vendors[<span class="st">'purchase_contribution_percentage'</span>].<span class="bu">sum</span>(), <span class="dv">2</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total Purchase Contribution of top 10 vendors is </span><span class="sc">{</span>total_contribution<span class="sc">}</span><span class="ss"> %"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total Purchase Contribution of top 10 vendors is 65.69 %</code></pre>
</div>
</div>
<p><strong>Key Insights:</strong> - Procurement is <strong>highly concentrated</strong>, with <strong>DIAGEO NORTH AMERICA INC</strong> alone contributing over <strong>16%</strong> of total purchases. - The <strong>donut chart</strong> clearly shows that nearly <strong>two-thirds</strong> of all purchase dollars flow through these top vendors. - Such dependence increases both <strong>bargaining leverage</strong> (for discounts) and <strong>risk exposure</strong> (in case of supply disruption).</p>
<p><strong>Business Implication:</strong> Strategic diversification could reduce procurement risk while maintaining favorable pricing relationships with key suppliers.</p>
<div id="1c6f0f20" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.colors <span class="im">as</span> mcolors</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>vendors <span class="op">=</span> <span class="bu">list</span>(top_vendors[<span class="st">'vendor_name'</span>].values)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>purchase_contributions <span class="op">=</span> <span class="bu">list</span>(top_vendors[<span class="st">'purchase_contribution_percentage'</span>].values)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate remaining contribution</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>remaining_contribution <span class="op">=</span> <span class="dv">100</span> <span class="op">-</span> total_contribution</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Append "Other Vendors" category</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>vendors.append(<span class="st">"Other Vendors"</span>)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>purchase_contributions.append(remaining_contribution)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Donut Chart ---</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">7</span>))  <span class="co"># a bit wider for legend</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _autopct_with_contrast(pct, all_vals):</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Determine index of this wedge</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> <span class="bu">sum</span>(all_vals)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    value <span class="op">=</span> pct <span class="op">*</span> total <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>pct<span class="sc">:.1f}</span><span class="ss">%"</span> <span class="cf">if</span> pct <span class="op">&gt;=</span> <span class="dv">3</span> <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_contrast_color(hex_color):</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    r, g, b <span class="op">=</span> mcolors.to_rgb(hex_color)</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    brightness <span class="op">=</span> (r<span class="op">*</span><span class="fl">0.299</span> <span class="op">+</span> g<span class="op">*</span><span class="fl">0.587</span> <span class="op">+</span> b<span class="op">*</span><span class="fl">0.114</span>)</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"#FFFFFF"</span> <span class="cf">if</span> brightness <span class="op">&lt;</span> <span class="fl">0.55</span> <span class="cf">else</span> <span class="st">"#000000"</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Show % labels only for slices above a threshold</span></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _autopct(pct):</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>pct<span class="sc">:.1f}</span><span class="ss">%"</span> <span class="cf">if</span> pct <span class="op">&gt;=</span> <span class="dv">3</span> <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">"#003366"</span>, <span class="st">"#005b96"</span>, <span class="st">"#6497b1"</span>, <span class="st">"#b3cde0"</span>, <span class="st">"#f0f0f0"</span>,</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>          <span class="st">"#ffcc00"</span>, <span class="st">"#ff9966"</span>, <span class="st">"#cc6666"</span>, <span class="st">"#9999cc"</span>, <span class="st">"#66cccc"</span>, <span class="st">"#e0e0e0"</span>]</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Use wedgeprops to make a donut directly (no separate white circle)</span></span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>wedges, texts, autotexts <span class="op">=</span> ax.pie(</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>    purchase_contributions,</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span><span class="va">None</span>,                        <span class="co"># move labels to legend (less clutter)</span></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>    autopct<span class="op">=</span><span class="kw">lambda</span> pct: _autopct_with_contrast(pct, purchase_contributions),</span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>    startangle<span class="op">=</span><span class="dv">90</span>,                      <span class="co"># standard for pies, reads better</span></span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>    pctdistance<span class="op">=</span><span class="fl">0.75</span>,                   <span class="co"># bring % inwards a touch</span></span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>    wedgeprops<span class="op">=</span>{<span class="st">"width"</span>: <span class="fl">0.35</span>, <span class="st">"edgecolor"</span>: <span class="st">"white"</span>},  <span class="co"># crisp separation</span></span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>    textprops<span class="op">=</span>{<span class="st">"fontsize"</span>: <span class="dv">10</span>},</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>    colors<span class="op">=</span> colors</span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, autotext <span class="kw">in</span> <span class="bu">enumerate</span>(autotexts):</span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>    autotext.set_color(get_contrast_color(colors[i]))</span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>    autotext.set_fontsize(<span class="dv">10</span>)</span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a>    autotext.set_fontweight(<span class="st">"bold"</span>)</span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure circle aspect</span></span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"equal"</span>)</span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Center text (total)</span></span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a>ax.text(</span>
<span id="cb30-59"><a href="#cb30-59" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>, <span class="dv">0</span>,</span>
<span id="cb30-60"><a href="#cb30-60" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Top 10 Total:</span><span class="ch">\n</span><span class="sc">{</span>total_contribution<span class="sc">:.2f}</span><span class="ss">%"</span>,</span>
<span id="cb30-61"><a href="#cb30-61" aria-hidden="true" tabindex="-1"></a>    ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb30-62"><a href="#cb30-62" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">"bold"</span></span>
<span id="cb30-63"><a href="#cb30-63" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-64"><a href="#cb30-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-65"><a href="#cb30-65" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a clean legend on the right with vendor name + % value</span></span>
<span id="cb30-66"><a href="#cb30-66" aria-hidden="true" tabindex="-1"></a><span class="co"># (Keeps plot uncluttered and ensures long names don't overlap)</span></span>
<span id="cb30-67"><a href="#cb30-67" aria-hidden="true" tabindex="-1"></a>legend_labels <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">}</span><span class="ss"> — </span><span class="sc">{</span>pc<span class="sc">:.1f}</span><span class="ss">%"</span> <span class="cf">for</span> v, pc <span class="kw">in</span> <span class="bu">zip</span>(vendors, purchase_contributions)]</span>
<span id="cb30-68"><a href="#cb30-68" aria-hidden="true" tabindex="-1"></a>ax.legend(</span>
<span id="cb30-69"><a href="#cb30-69" aria-hidden="true" tabindex="-1"></a>    wedges,</span>
<span id="cb30-70"><a href="#cb30-70" aria-hidden="true" tabindex="-1"></a>    legend_labels,</span>
<span id="cb30-71"><a href="#cb30-71" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Vendors"</span>,</span>
<span id="cb30-72"><a href="#cb30-72" aria-hidden="true" tabindex="-1"></a>    loc<span class="op">=</span><span class="st">"center left"</span>,</span>
<span id="cb30-73"><a href="#cb30-73" aria-hidden="true" tabindex="-1"></a>    bbox_to_anchor<span class="op">=</span>(<span class="fl">1.02</span>, <span class="fl">0.5</span>),</span>
<span id="cb30-74"><a href="#cb30-74" aria-hidden="true" tabindex="-1"></a>    frameon<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb30-75"><a href="#cb30-75" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb30-76"><a href="#cb30-76" aria-hidden="true" tabindex="-1"></a>    title_fontsize<span class="op">=</span><span class="dv">11</span></span>
<span id="cb30-77"><a href="#cb30-77" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-78"><a href="#cb30-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-79"><a href="#cb30-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Title + subtle subtitle</span></span>
<span id="cb30-80"><a href="#cb30-80" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Top 10 Vendors' Purchase Contribution (%)"</span>, pad<span class="op">=</span><span class="dv">16</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-81"><a href="#cb30-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-82"><a href="#cb30-82" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb30-83"><a href="#cb30-83" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-26-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-2-does-purchasing-in-bulk-reduce-the-unit-price" class="level3">
<h3 class="anchored" data-anchor-id="question-2-does-purchasing-in-bulk-reduce-the-unit-price">Question 2 — Does purchasing in bulk reduce the unit price?</h3>
<p>To evaluate the <strong>impact of order size on unit purchase price</strong>, purchases were grouped into <strong>Small</strong>, <strong>Medium</strong>, and <strong>Large</strong> quantile-based categories.</p>
<div id="2a22db5c" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'unit_purchase_price'</span>]<span class="op">=</span>df[<span class="st">'total_purchase_dollars'</span>]<span class="op">/</span>df[<span class="st">'total_purchase_quantity'</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co">#creating 3 equal quantile buckets.</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'order_size'</span>]<span class="op">=</span> pd.qcut(df[<span class="st">'total_purchase_quantity'</span>], q<span class="op">=</span><span class="dv">3</span>, labels<span class="op">=</span>[<span class="st">"Small"</span>, <span class="st">"Medium"</span>, <span class="st">"Large"</span>])</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">'order_size'</span>, <span class="st">'total_purchase_quantity'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">order_size</th>
<th data-quarto-table-cell-role="th">total_purchase_quantity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Large</td>
<td>145080.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Large</td>
<td>164038.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Large</td>
<td>187407.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Large</td>
<td>201682.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Large</td>
<td>138109.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8559</td>
<td>Small</td>
<td>2.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8560</td>
<td>Small</td>
<td>6.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8561</td>
<td>Small</td>
<td>2.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8562</td>
<td>Small</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8563</td>
<td>Small</td>
<td>1.0</td>
</tr>
</tbody>
</table>

<p>8564 rows × 2 columns</p>
</div>
</div>
</div>
<p>calculating mean for each category</p>
<div id="e8426ff1" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df.groupby(<span class="st">'order_size'</span>)[[<span class="st">'unit_purchase_price'</span>]].mean()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">"order_size"</span>, y<span class="op">=</span><span class="st">"unit_purchase_price"</span>, palette<span class="op">=</span><span class="st">"Set2"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Impact of Bulk Purchasing on Unit Price"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Order size"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"average unit purchase price"</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Findings:</strong> - <strong>Large orders</strong> have the <strong>lowest average unit price (~$10.78 per unit)</strong>, confirming the effect of <strong>economies of scale</strong>. - The <strong>price difference</strong> between Small and Large orders is significant — roughly a <strong>72% reduction</strong> in cost per unit. - This suggests vendors offering volume-based pricing effectively <strong>incentivize bulk purchasing</strong>, leading to <strong>higher total sales</strong> despite lower per-unit revenue.</p>
<p><strong>Business Takeaway:</strong> Bulk purchasing is <strong>cost-efficient</strong> and should be leveraged where feasible. However, it must be balanced against <strong>inventory holding costs</strong> and <strong>cash flow constraints</strong> to ensure sustainable profitability.</p>
</section>
</section>
<section id="analysis-5-inventory-turnover-and-capital-locked-in-unsold-stock" class="level2">
<h2 class="anchored" data-anchor-id="analysis-5-inventory-turnover-and-capital-locked-in-unsold-stock">📦 Analysis 5 — Inventory Turnover and Capital Locked in Unsold Stock</h2>
<p><strong>Business Objective:</strong> Identify vendors with <strong>low stock turnover</strong> (slow-moving products) and estimate the <strong>capital tied up in unsold inventory</strong>.</p>
<hr>
<section id="low-inventory-turnover" class="level3">
<h3 class="anchored" data-anchor-id="low-inventory-turnover">🔄 Low Inventory Turnover</h3>
<p>The vendors below have an <strong>average stock turnover below 1</strong>, indicating <strong>slow-moving or stagnant inventory</strong>. This may signal <strong>over-purchasing</strong>, <strong>weak demand</strong>, or <strong>inefficient stock rotation</strong>.</p>
<p><strong>Lowest Turnover Vendors:</strong> - ALISA CARR BEVERAGES — 0.62 - HIGHLAND WINE MERCHANTS LLC — 0.71 - PARK STREET IMPORTS LLC — 0.75 - DUNN WINE BROKERS — 0.77 - TAMWORTH DISTILLING — 0.80</p>
<p><strong>Interpretation:</strong> A stock turnover below 1 means these vendors sell their entire inventory <strong>less than once per year</strong>, leading to excess holding costs and reduced liquidity.</p>
<hr>
<div id="d1e14de8" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df[df[<span class="st">'stock_turnover'</span>]<span class="op">&lt;</span><span class="dv">1</span>].groupby(<span class="st">'vendor_name'</span>)[[<span class="st">'stock_turnover'</span>]].mean().sort_values(<span class="st">'stock_turnover'</span>, ascending<span class="op">=</span><span class="va">True</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">stock_turnover</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">vendor_name</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">ALISA CARR BEVERAGES</td>
<td>0.615385</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">HIGHLAND WINE MERCHANTS LLC</td>
<td>0.708333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">PARK STREET IMPORTS LLC</td>
<td>0.751306</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Circa Wines</td>
<td>0.755676</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dunn Wine Brokers</td>
<td>0.766022</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CENTEUR IMPORTS LLC</td>
<td>0.773953</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">SMOKY QUARTZ DISTILLERY LLC</td>
<td>0.783835</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">TAMWORTH DISTILLING</td>
<td>0.797078</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">THE IMPORTED GRAPE LLC</td>
<td>0.807569</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">WALPOLE MTN VIEW WINERY</td>
<td>0.820548</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
<section id="capital-locked-in-unsold-inventory" class="level3">
<h3 class="anchored" data-anchor-id="capital-locked-in-unsold-inventory">💰 Capital Locked in Unsold Inventory</h3>
<p>Across all vendors, the <strong>total unsold capital</strong> amounts to approximately <strong>$2.71M</strong>, representing the value of stock purchased but not yet sold.</p>
<p><strong>Top Vendors by Unsold Capital:</strong> - DIAGEO NORTH AMERICA INC — <strong>$722K</strong> - JIM BEAM BRANDS COMPANY — <strong>$555K</strong> - PERNOD RICARD USA — <strong>$471K</strong> - WILLIAM GRANT &amp; SONS INC — <strong>$402K</strong> - E &amp; J GALLO WINERY — <strong>$228K</strong></p>
<hr>
<div id="49fab938" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'unsold_inventory_value'</span>]<span class="op">=</span>(df[<span class="st">'total_purchase_quantity'</span>]<span class="op">-</span>df[<span class="st">'total_sales_quantity'</span>])<span class="op">*</span> df[<span class="st">'purchase_price'</span>]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'total_unsold_capital:'</span>, format_dollars(df[<span class="st">'unsold_inventory_value'</span>].<span class="bu">sum</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total_unsold_capital: 2.71M</code></pre>
</div>
</div>
<div id="09ec3d26" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate Capital Locked per Vendor</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>inventory_value_per_vendor <span class="op">=</span> df.groupby(<span class="st">"vendor_name"</span>)[<span class="st">"unsold_inventory_value"</span>].<span class="bu">sum</span>().reset_index()</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort Vendors with the Highest Locked Capital</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>inventory_value_per_vendor <span class="op">=</span> inventory_value_per_vendor.sort_values(by<span class="op">=</span><span class="st">"unsold_inventory_value"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>inventory_value_per_vendor[<span class="st">'unsold_inventory_value'</span>] <span class="op">=</span> inventory_value_per_vendor[<span class="st">'unsold_inventory_value'</span>].<span class="bu">apply</span>(format_dollars)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>inventory_value_per_vendor.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">vendor_name</th>
<th data-quarto-table-cell-role="th">unsold_inventory_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">25</td>
<td>DIAGEO NORTH AMERICA INC</td>
<td>722.21k</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">46</td>
<td>JIM BEAM BRANDS COMPANY</td>
<td>554.67k</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">68</td>
<td>PERNOD RICARD USA</td>
<td>470.63k</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">116</td>
<td>WILLIAM GRANT &amp; SONS INC</td>
<td>401.96k</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>E &amp; J GALLO WINERY</td>
<td>228.28k</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">79</td>
<td>SAZERAC CO INC</td>
<td>198.44k</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>BROWN-FORMAN CORP</td>
<td>177.73k</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">20</td>
<td>CONSTELLATION BRANDS INC</td>
<td>133.62k</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">61</td>
<td>MOET HENNESSY USA INC</td>
<td>126.48k</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">77</td>
<td>REMY COINTREAU USA INC</td>
<td>118.60k</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="insights-1" class="level3">
<h3 class="anchored" data-anchor-id="insights-1">📈 Insights</h3>
<ul>
<li>A significant share of capital is tied up in <strong>inventory from top-performing vendors</strong>, implying potential overstocking.</li>
<li>Slow-moving products could benefit from <strong>discounting</strong>, <strong>bundling</strong>, or <strong>targeted promotions</strong> to clear excess inventory.</li>
<li>Continuous monitoring of <strong>stock turnover ratio</strong> is crucial to maintain <strong>optimal working capital efficiency</strong>.</li>
</ul>
<hr>
<p><strong>Summary:</strong> Approximately <strong>$2.71M</strong> is locked in unsold stock, with several large vendors contributing most of it. Improving turnover through <strong>inventory management and demand forecasting</strong> can free up capital and improve cash flow.</p>
</section>
</section>
<section id="analysis-6-profit-margin-confidence-intervals-for-top-vs.-low-vendors" class="level2">
<h2 class="anchored" data-anchor-id="analysis-6-profit-margin-confidence-intervals-for-top-vs.-low-vendors">💹 Analysis 6 — Profit Margin Confidence Intervals for Top vs.&nbsp;Low Vendors</h2>
<p><strong>Business Objective:</strong> Compare profit margins between <strong>top-performing vendors (high sales)</strong> and <strong>low-performing vendors (low sales)</strong> to understand profitability patterns.</p>
<div id="5ca16b1d" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>top_threshold<span class="op">=</span> df[<span class="st">'total_sales_dollars'</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>low_threshold<span class="op">=</span> df[<span class="st">'total_sales_dollars'</span>].quantile(<span class="fl">0.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="f505e551" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>top_vendors <span class="op">=</span> df[df[<span class="st">"total_sales_dollars"</span>] <span class="op">&gt;=</span> top_threshold][<span class="st">"profit_margin"</span>].dropna()</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>low_vendors <span class="op">=</span> df[df[<span class="st">"total_sales_dollars"</span>] <span class="op">&lt;=</span> low_threshold][<span class="st">"profit_margin"</span>].dropna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<section id="statistical-summary" class="level3">
<h3 class="anchored" data-anchor-id="statistical-summary">🧮 Statistical Summary</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Vendor Group</th>
<th>Mean Profit Margin (%)</th>
<th>95% Confidence Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Top Vendors</td>
<td>31.18</td>
<td>(30.74, 31.61)</td>
</tr>
<tr class="even">
<td>Low Vendors</td>
<td>41.57</td>
<td>(40.50, 42.64)</td>
</tr>
</tbody>
</table>
<hr>
<div id="dbbbd63e" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to calculate the confidence interval</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> confidence_interval(data, confidence<span class="op">=</span><span class="fl">0.95</span>):</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    mean_val<span class="op">=</span>np.mean(data)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    std_err<span class="op">=</span>np.std(data,ddof<span class="op">=</span><span class="dv">1</span>)<span class="op">/</span>np.sqrt(<span class="bu">len</span>(data)) <span class="co">#standard error</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    t_critical<span class="op">=</span>stats.t.ppf((<span class="dv">1</span><span class="op">+</span>confidence)<span class="op">/</span><span class="dv">2</span>, df<span class="op">=</span><span class="bu">len</span>(data)<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    margin_of_error<span class="op">=</span> t_critical <span class="op">*</span>std_err</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> mean_val, mean_val<span class="op">-</span>margin_of_error, mean_val<span class="op">+</span>margin_of_error</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="1cd662af" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute confidence intervals for top and low vendors</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>top_mean, top_lower, top_upper <span class="op">=</span> confidence_interval(top_vendors)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>low_mean, low_lower, low_upper <span class="op">=</span> confidence_interval(low_vendors)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Top Vendors 95% CI: (</span><span class="sc">{</span>top_lower<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>top_upper<span class="sc">:.2f}</span><span class="ss">), Mean: </span><span class="sc">{</span>top_mean<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Low Vendors 95% CI: (</span><span class="sc">{</span>low_lower<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>low_upper<span class="sc">:.2f}</span><span class="ss">), Mean: </span><span class="sc">{</span>low_mean<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot comparison</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Top Vendors Plot ---</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>sns.histplot(top_vendors, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"blue"</span>, bins<span class="op">=</span><span class="dv">30</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">"Top Vendors"</span>)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>plt.axvline(top_lower, color<span class="op">=</span><span class="st">"blue"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"Top Lower: </span><span class="sc">{</span>top_lower<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>plt.axvline(top_upper, color<span class="op">=</span><span class="st">"blue"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"Top Upper: </span><span class="sc">{</span>top_upper<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>plt.axvline(top_mean, color<span class="op">=</span><span class="st">"blue"</span>, linestyle<span class="op">=</span><span class="st">"-"</span>, label<span class="op">=</span><span class="ss">f"Top Mean: </span><span class="sc">{</span>top_mean<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Low Vendors Plot ---</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>sns.histplot(low_vendors, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"red"</span>, bins<span class="op">=</span><span class="dv">30</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">"Low Vendors"</span>)</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>plt.axvline(low_lower, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"Low Lower: </span><span class="sc">{</span>low_lower<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>plt.axvline(low_upper, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"Low Upper: </span><span class="sc">{</span>low_upper<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>plt.axvline(low_mean, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"-"</span>, label<span class="op">=</span><span class="ss">f"Low Mean: </span><span class="sc">{</span>low_mean<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Finalize Plot ---</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Confidence Interval Comparison: Top vs. Low Vendors (Profit Margin)"</span>)</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Profit Margin (%)"</span>)</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Top Vendors 95% CI: (30.74, 31.61), Mean: 31.18
Low Vendors 95% CI: (40.50, 42.64), Mean: 41.57</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06_retail-vendor-performance-Analysis_files/figure-html/cell-35-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="insights-from-the-distribution" class="level3">
<h3 class="anchored" data-anchor-id="insights-from-the-distribution">📊 Insights from the Distribution</h3>
<ul>
<li><strong>Low-performing vendors</strong> exhibit <strong>higher average profit margins (≈41.6%)</strong>, suggesting they rely on <strong>premium pricing</strong> or smaller, high-margin product lines.</li>
<li><strong>Top-performing vendors</strong>, despite higher total sales, maintain <strong>lower margins (≈31.2%)</strong>, likely due to <strong>volume-driven pricing</strong> or <strong>competitive markets</strong>.</li>
<li>The <strong>non-overlapping confidence intervals</strong> confirm that the difference is <strong>statistically significant</strong> — low vendors indeed have higher margins.</li>
<li><strong>Distribution Shape:</strong> Both groups show right-skewed distributions, with low vendors having a broader spread due to niche product pricing.</li>
</ul>
<hr>
</section>
<section id="business-implications" class="level3">
<h3 class="anchored" data-anchor-id="business-implications">💡 Business Implications</h3>
<ul>
<li><strong>High-performing vendors:</strong> Should explore <strong>cost optimization</strong>, <strong>tiered pricing</strong>, or <strong>product bundling</strong> to improve margins without hurting volume.</li>
<li><strong>Low-performing vendors:</strong> Could increase total revenue by <strong>expanding reach</strong>, <strong>improving distribution</strong>, or <strong>competitive pricing</strong>, since they already maintain healthy margins.</li>
</ul>
<hr>
<p><strong>Summary:</strong> Top vendors drive revenue but with tighter margins, while smaller vendors sustain profitability through higher markups. Balancing both strategies can optimize <strong>overall portfolio profitability</strong>.</p>
</section>
</section>
<section id="analysis-7-hypothesis-testing-profit-margin-differences-between-vendor-groups" class="level2">
<h2 class="anchored" data-anchor-id="analysis-7-hypothesis-testing-profit-margin-differences-between-vendor-groups">🧾 Analysis 7 — Hypothesis Testing: Profit Margin Differences Between Vendor Groups</h2>
<p><strong>Objective:</strong> Test whether the difference in <strong>mean profit margins</strong> between <strong>top-performing</strong> and <strong>low-performing</strong> vendors is statistically significant.</p>
<hr>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">🧠 Hypotheses</h3>
<ul>
<li><strong>H₀ (Null Hypothesis):</strong> There is <strong>no significant difference</strong> in the mean profit margins of top- and low-performing vendors.</li>
<li><strong>H₁ (Alternative Hypothesis):</strong> There <strong>is a significant difference</strong> in the mean profit margins of top- and low-performing vendors.</li>
</ul>
<hr>
</section>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method">⚙️ Method</h3>
<p>A <strong>two-sample independent t-test (unequal variances)</strong> was conducted using vendor-level profit margins: - <strong>Top Vendors:</strong> Sales above the 75th percentile - <strong>Low Vendors:</strong> Sales below the 25th percentile</p>
<hr>
<div id="d1a1a7d8" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define thresholds for top and low vendors (based on quartiles)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>top_threshold <span class="op">=</span> df[<span class="st">"total_sales_dollars"</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>low_threshold <span class="op">=</span> df[<span class="st">"total_sales_dollars"</span>].quantile(<span class="fl">0.25</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Split vendors into top and low based on sales</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>top_vendors <span class="op">=</span> df[df[<span class="st">"total_sales_dollars"</span>] <span class="op">&gt;=</span> top_threshold][<span class="st">"profit_margin"</span>].dropna()</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>low_vendors <span class="op">=</span> df[df[<span class="st">"total_sales_dollars"</span>] <span class="op">&lt;=</span> low_threshold][<span class="st">"profit_margin"</span>].dropna()</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Two-Sample T-Test</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>t_stat, p_value <span class="op">=</span> ttest_ind(top_vendors, low_vendors, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-Statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.4f}</span><span class="ss">, P-Value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Reject H₀: There is a significant difference in profit margins between top and low-performing vendors."</span>)</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Fail to Reject H₀: No significant difference in profit margins."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-Statistic: -17.6695, P-Value: 0.0000
Reject H₀: There is a significant difference in profit margins between top and low-performing vendors.</code></pre>
</div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">📊 Results</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>T-Statistic</strong></td>
<td style="text-align: left;">-17.67</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>P-Value</strong></td>
<td style="text-align: left;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Decision</strong></td>
<td style="text-align: left;">Reject H₀</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong> The p-value (&lt; 0.05) confirms a <strong>statistically significant difference</strong> in mean profit margins between the two vendor groups. Low-performing vendors maintain <strong>significantly higher profit margins</strong> compared to top-performing vendors.</p>
<hr>
</section>
<section id="business-insight-1" class="level3">
<h3 class="anchored" data-anchor-id="business-insight-1">💡 Business Insight</h3>
<ul>
<li><strong>Top Vendors:</strong> Operate on <strong>high volume but thinner margins</strong>, consistent with competitive pricing strategies.</li>
<li><strong>Low Vendors:</strong> Maintain <strong>lower sales but higher markups</strong>, reflecting premium positioning or niche markets.</li>
<li>The results support a <strong>dual strategy</strong>:
<ul>
<li>Optimize costs and efficiency for high-volume vendors.</li>
<li>Expand marketing and visibility for high-margin, low-volume vendors to unlock additional revenue potential.</li>
</ul></li>
</ul>
<hr>
<p><strong>Conclusion:</strong> The difference in profit margins between top and low-performing vendors is <strong>statistically significant</strong>, indicating distinct business models driving performance in each group.</p>
<hr>
</section>
</section>
<section id="author" class="level2">
<h2 class="anchored" data-anchor-id="author">👋 Author</h2>
<p><strong>Yash Tiwari</strong> <br> <em>Data | Product | Strategy | Design</em> <br> 📊 Data Analyst &amp; Business Analyst — 🏗️ builder @ ❤️ <br><br> 📧 <a href="mailto:yashtiwari.ty@gmail.com">yashtiwari.ty@gmail.com</a> <br> 🌐 <a href="https://www.linkedin.com/in/yash-tiwari-here/">LinkedIn</a> • <a href="https://leaf-allspice-531.notion.site/Hey-there-I-am-Yash-28a9c4819e1680a48f15c39ad54bd9d6?source=copy_link">Portfolio</a></p>
<hr>
<blockquote class="blockquote">
<p><em>I build data stories that drive product, strategy, and design decisions.</em> <em>Passionate about blending analytical rigor with creative problem-solving.</em></p>
</blockquote>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>